/*
 * Code below this message is generated by openpmx (https://github.com/deleveld/openpmx).
 * Copyright (c) 2024 Douglas Eleveld.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#include <math.h>
#include <stdlib.h>
#include <stddef.h>
#include <assert.h>
//#define _GNU_SOURCE
//#include <fenv.h>
#include "openpmx.h"

#define OPENPMXTRAN_DEFAULT_FILENAME \
"warfarin.gr"

/* begin OPENPMXTRAN_DATA_ARRAY */
typedef struct RECORD {
	double ID, time, wt, age, sex, amt, rate, dvid, dv, mdv;
} RECORD;
RECORD OPENPMXTRAN_DATA_NAME[] = {
	{	0,0,66.7,50,1,100,0,0,NAN,1	},
	{	0,0,66.7,50,1,NAN,NAN,2,NAN,1	},
	{	0,0.5,66.7,50,1,NAN,NAN,1,0,0	},
	{	0,1,66.7,50,1,NAN,NAN,1,1.9,0	},
	{	0,2,66.7,50,1,NAN,NAN,1,3.3,0	},
	{	0,3,66.7,50,1,NAN,NAN,1,6.6,0	},
	{	0,6,66.7,50,1,NAN,NAN,1,9.1,0	},
	{	0,9,66.7,50,1,NAN,NAN,1,10.8,0	},
	{	0,12,66.7,50,1,NAN,NAN,1,8.6,0	},
	{	0,24,66.7,50,1,NAN,NAN,1,5.6,0	},
	{	0,24,66.7,50,1,NAN,NAN,2,44,0	},
	{	0,36,66.7,50,1,NAN,NAN,1,4,0	},
	{	0,36,66.7,50,1,NAN,NAN,2,27,0	},
	{	0,48,66.7,50,1,NAN,NAN,1,2.7,0	},
	{	0,48,66.7,50,1,NAN,NAN,2,28,0	},
	{	0,72,66.7,50,1,NAN,NAN,1,0.8,0	},
	{	0,72,66.7,50,1,NAN,NAN,2,31,0	},
	{	0,96,66.7,50,1,NAN,NAN,1,NAN,1	},
	{	0,96,66.7,50,1,NAN,NAN,2,60,0	},
	{	0,120,66.7,50,1,NAN,NAN,1,NAN,1	},
	{	0,120,66.7,50,1,NAN,NAN,2,65,0	},
	{	0,144,66.7,50,1,NAN,NAN,2,71,0	},
	{	1,0,66.7,50,1,100,0,0,NAN,1	},
	{	1,0,66.7,50,1,NAN,NAN,2,100,0	},
	{	1,24,66.7,50,1,NAN,NAN,1,9.2,0	},
	{	1,24,66.7,50,1,NAN,NAN,2,49,0	},
	{	1,36,66.7,50,1,NAN,NAN,1,8.5,0	},
	{	1,36,66.7,50,1,NAN,NAN,2,32,0	},
	{	1,48,66.7,50,1,NAN,NAN,1,6.4,0	},
	{	1,48,66.7,50,1,NAN,NAN,2,26,0	},
	{	1,72,66.7,50,1,NAN,NAN,1,4.8,0	},
	{	1,72,66.7,50,1,NAN,NAN,2,22,0	},
	{	1,96,66.7,50,1,NAN,NAN,1,3.1,0	},
	{	1,96,66.7,50,1,NAN,NAN,2,28,0	},
	{	1,120,66.7,50,1,NAN,NAN,1,2.5,0	},
	{	1,120,66.7,50,1,NAN,NAN,2,33,0	},
	{	2,0,66.7,31,1,100,0,0,NAN,1	},
	{	2,0,66.7,31,1,NAN,NAN,2,100,0	},
	{	2,0.5,66.7,31,1,NAN,NAN,1,0,0	},
	{	2,2,66.7,31,1,NAN,NAN,1,8.4,0	},
	{	2,3,66.7,31,1,NAN,NAN,1,9.7,0	},
	{	2,6,66.7,31,1,NAN,NAN,1,9.8,0	},
	{	2,12,66.7,31,1,NAN,NAN,1,11,0	},
	{	2,24,66.7,31,1,NAN,NAN,1,8.3,0	},
	{	2,24,66.7,31,1,NAN,NAN,2,46,0	},
	{	2,36,66.7,31,1,NAN,NAN,1,7.7,0	},
	{	2,36,66.7,31,1,NAN,NAN,2,22,0	},
	{	2,48,66.7,31,1,NAN,NAN,1,6.3,0	},
	{	2,48,66.7,31,1,NAN,NAN,2,19,0	},
	{	2,72,66.7,31,1,NAN,NAN,1,4.1,0	},
	{	2,72,66.7,31,1,NAN,NAN,2,20,0	},
	{	2,96,66.7,31,1,NAN,NAN,1,3,0	},
	{	2,96,66.7,31,1,NAN,NAN,2,42,0	},
	{	2,120,66.7,31,1,NAN,NAN,1,1.4,0	},
	{	2,120,66.7,31,1,NAN,NAN,2,49,0	},
	{	2,144,66.7,31,1,NAN,NAN,2,54,0	},
	{	3,0,80,40,1,120,0,0,NAN,1	},
	{	3,0,80,40,1,NAN,NAN,2,100,0	},
	{	3,3,80,40,1,NAN,NAN,1,12,0	},
	{	3,6,80,40,1,NAN,NAN,1,13.2,0	},
	{	3,9,80,40,1,NAN,NAN,1,14.4,0	},
	{	3,24,80,40,1,NAN,NAN,1,9.6,0	},
	{	3,24,80,40,1,NAN,NAN,2,30,0	},
	{	3,36,80,40,1,NAN,NAN,1,8.2,0	},
	{	3,36,80,40,1,NAN,NAN,2,24,0	},
	{	3,48,80,40,1,NAN,NAN,1,7.8,0	},
	{	3,48,80,40,1,NAN,NAN,2,13,0	},
	{	3,72,80,40,1,NAN,NAN,1,5.8,0	},
	{	3,72,80,40,1,NAN,NAN,2,9,0	},
	{	3,96,80,40,1,NAN,NAN,1,4.3,0	},
	{	3,96,80,40,1,NAN,NAN,2,9,0	},
	{	3,120,80,40,1,NAN,NAN,1,3,0	},
	{	3,120,80,40,1,NAN,NAN,2,11,0	},
	{	3,144,80,40,1,NAN,NAN,2,12,0	},
	{	4,0,40,46,0,60,0,0,NAN,1	},
	{	4,0,40,46,0,NAN,NAN,2,82,0	},
	{	4,3,40,46,0,NAN,NAN,1,11.1,0	},
	{	4,6,40,46,0,NAN,NAN,1,11.9,0	},
	{	4,9,40,46,0,NAN,NAN,1,9.8,0	},
	{	4,12,40,46,0,NAN,NAN,1,11,0	},
	{	4,24,40,46,0,NAN,NAN,1,8.5,0	},
	{	4,24,40,46,0,NAN,NAN,2,43,0	},
	{	4,36,40,46,0,NAN,NAN,1,7.6,0	},
	{	4,36,40,46,0,NAN,NAN,2,25,0	},
	{	4,48,40,46,0,NAN,NAN,1,5.4,0	},
	{	4,48,40,46,0,NAN,NAN,2,18,0	},
	{	4,72,40,46,0,NAN,NAN,1,4.5,0	},
	{	4,72,40,46,0,NAN,NAN,2,17,0	},
	{	4,96,40,46,0,NAN,NAN,1,3.3,0	},
	{	4,96,40,46,0,NAN,NAN,2,23,0	},
	{	4,120,40,46,0,NAN,NAN,1,2.3,0	},
	{	4,120,40,46,0,NAN,NAN,2,29,0	},
	{	4,144,40,46,0,NAN,NAN,2,41,0	},
	{	5,0,75.3,43,1,113,0,0,NAN,1	},
	{	5,0,75.3,43,1,NAN,NAN,2,100,0	},
	{	5,6,75.3,43,1,NAN,NAN,1,8.6,0	},
	{	5,12,75.3,43,1,NAN,NAN,1,8.6,0	},
	{	5,24,75.3,43,1,NAN,NAN,1,7,0	},
	{	5,24,75.3,43,1,NAN,NAN,2,34,0	},
	{	5,36,75.3,43,1,NAN,NAN,1,5.7,0	},
	{	5,36,75.3,43,1,NAN,NAN,2,23,0	},
	{	5,48,75.3,43,1,NAN,NAN,1,4.7,0	},
	{	5,48,75.3,43,1,NAN,NAN,2,20,0	},
	{	5,72,75.3,43,1,NAN,NAN,1,3.3,0	},
	{	5,72,75.3,43,1,NAN,NAN,2,16,0	},
	{	5,96,75.3,43,1,NAN,NAN,1,2.3,0	},
	{	5,96,75.3,43,1,NAN,NAN,2,17,0	},
	{	5,120,75.3,43,1,NAN,NAN,1,1.7,0	},
	{	5,120,75.3,43,1,NAN,NAN,2,18,0	},
	{	5,144,75.3,43,1,NAN,NAN,2,25,0	},
	{	6,0,60,36,0,90,0,0,NAN,1	},
	{	6,3,60,36,0,NAN,NAN,1,13.4,0	},
	{	6,6,60,36,0,NAN,NAN,1,12.4,0	},
	{	6,9,60,36,0,NAN,NAN,1,12.7,0	},
	{	6,12,60,36,0,NAN,NAN,1,8.8,0	},
	{	6,24,60,36,0,NAN,NAN,1,6.1,0	},
	{	6,24,60,36,0,NAN,NAN,2,36,0	},
	{	6,36,60,36,0,NAN,NAN,1,3.5,0	},
	{	6,36,60,36,0,NAN,NAN,2,33,0	},
	{	6,48,60,36,0,NAN,NAN,1,1.8,0	},
	{	6,48,60,36,0,NAN,NAN,2,28,0	},
	{	6,72,60,36,0,NAN,NAN,1,1.5,0	},
	{	6,72,60,36,0,NAN,NAN,2,52,0	},
	{	6,96,60,36,0,NAN,NAN,1,1,0	},
	{	6,96,60,36,0,NAN,NAN,2,80,0	},
	{	6,120,60,36,0,NAN,NAN,1,NAN,1	},
	{	6,120,60,36,0,NAN,NAN,2,90,0	},
	{	6,144,60,36,0,NAN,NAN,2,100,0	},
	{	7,0,90,41,1,135,0,0,NAN,1	},
	{	7,0,90,41,1,NAN,NAN,2,88,0	},
	{	7,2,90,41,1,NAN,NAN,1,17.6,0	},
	{	7,3,90,41,1,NAN,NAN,1,17.3,0	},
	{	7,6,90,41,1,NAN,NAN,1,15,0	},
	{	7,9,90,41,1,NAN,NAN,1,15,0	},
	{	7,12,90,41,1,NAN,NAN,1,12.4,0	},
	{	7,24,90,41,1,NAN,NAN,1,7.9,0	},
	{	7,24,90,41,1,NAN,NAN,2,35,0	},
	{	7,36,90,41,1,NAN,NAN,1,7.9,0	},
	{	7,36,90,41,1,NAN,NAN,2,20,0	},
	{	7,48,90,41,1,NAN,NAN,1,5.1,0	},
	{	7,48,90,41,1,NAN,NAN,2,12,0	},
	{	7,72,90,41,1,NAN,NAN,1,3.6,0	},
	{	7,72,90,41,1,NAN,NAN,2,16,0	},
	{	7,96,90,41,1,NAN,NAN,1,2.4,0	},
	{	7,96,90,41,1,NAN,NAN,2,23,0	},
	{	7,120,90,41,1,NAN,NAN,1,2,0	},
	{	7,120,90,41,1,NAN,NAN,2,36,0	},
	{	7,144,90,41,1,NAN,NAN,2,48,0	},
	{	8,0,50,27,0,75,0,0,NAN,1	},
	{	8,0,50,27,0,NAN,NAN,2,92,0	},
	{	8,0.5,50,27,0,NAN,NAN,1,0,0	},
	{	8,1,50,27,0,NAN,NAN,1,1,0	},
	{	8,2,50,27,0,NAN,NAN,1,4.6,0	},
	{	8,3,50,27,0,NAN,NAN,1,12.7,0	},
	{	8,3,50,27,0,NAN,NAN,1,8,0	},
	{	8,6,50,27,0,NAN,NAN,1,12.7,0	},
	{	8,6,50,27,0,NAN,NAN,1,11.5,0	},
	{	8,9,50,27,0,NAN,NAN,1,12.9,0	},
	{	8,9,50,27,0,NAN,NAN,1,11.4,0	},
	{	8,12,50,27,0,NAN,NAN,1,11.4,0	},
	{	8,12,50,27,0,NAN,NAN,1,11,0	},
	{	8,24,50,27,0,NAN,NAN,1,9.1,0	},
	{	8,24,50,27,0,NAN,NAN,2,33,0	},
	{	8,36,50,27,0,NAN,NAN,1,8.2,0	},
	{	8,36,50,27,0,NAN,NAN,2,22,0	},
	{	8,48,50,27,0,NAN,NAN,1,5.9,0	},
	{	8,48,50,27,0,NAN,NAN,2,16,0	},
	{	8,72,50,27,0,NAN,NAN,1,3.6,0	},
	{	8,72,50,27,0,NAN,NAN,2,18,0	},
	{	8,96,50,27,0,NAN,NAN,1,1.7,0	},
	{	8,96,50,27,0,NAN,NAN,2,32,0	},
	{	8,120,50,27,0,NAN,NAN,1,1.1,0	},
	{	8,120,50,27,0,NAN,NAN,2,30,0	},
	{	8,144,50,27,0,NAN,NAN,2,45,0	},
	{	9,0,70,28,1,105,0,0,NAN,1	},
	{	9,0,70,28,1,NAN,NAN,2,90,0	},
	{	9,24,70,28,1,NAN,NAN,1,8.6,0	},
	{	9,24,70,28,1,NAN,NAN,2,39,0	},
	{	9,36,70,28,1,NAN,NAN,1,8,0	},
	{	9,36,70,28,1,NAN,NAN,2,22,0	},
	{	9,48,70,28,1,NAN,NAN,1,6,0	},
	{	9,48,70,28,1,NAN,NAN,2,17,0	},
	{	9,72,70,28,1,NAN,NAN,1,4.4,0	},
	{	9,72,70,28,1,NAN,NAN,2,17,0	},
	{	9,96,70,28,1,NAN,NAN,1,3.6,0	},
	{	9,96,70,28,1,NAN,NAN,2,22,0	},
	{	9,120,70,28,1,NAN,NAN,1,2.8,0	},
	{	9,120,70,28,1,NAN,NAN,2,25,0	},
	{	9,144,70,28,1,NAN,NAN,2,33,0	},
	{	11,0,82,31,1,123,0,0,NAN,1	},
	{	11,0,82,31,1,NAN,NAN,2,100,0	},
	{	11,1.5,82,31,1,NAN,NAN,1,11.4,0	},
	{	11,3,82,31,1,NAN,NAN,1,15.4,0	},
	{	11,6,82,31,1,NAN,NAN,1,17.5,0	},
	{	11,12,82,31,1,NAN,NAN,1,14,0	},
	{	11,24,82,31,1,NAN,NAN,1,9,0	},
	{	11,24,82,31,1,NAN,NAN,2,37,0	},
	{	11,36,82,31,1,NAN,NAN,1,8.9,0	},
	{	11,36,82,31,1,NAN,NAN,2,24,0	},
	{	11,48,82,31,1,NAN,NAN,1,6.6,0	},
	{	11,48,82,31,1,NAN,NAN,2,14,0	},
	{	11,72,82,31,1,NAN,NAN,1,4.2,0	},
	{	11,72,82,31,1,NAN,NAN,2,11,0	},
	{	11,96,82,31,1,NAN,NAN,1,3.6,0	},
	{	11,96,82,31,1,NAN,NAN,2,14,0	},
	{	11,120,82,31,1,NAN,NAN,1,2.6,0	},
	{	11,120,82,31,1,NAN,NAN,2,23,0	},
	{	11,144,82,31,1,NAN,NAN,2,33,0	},
	{	12,0,75.3,32,1,113,0,0,NAN,1	},
	{	12,0,75.3,32,1,NAN,NAN,2,85,0	},
	{	12,1.5,75.3,32,1,NAN,NAN,1,0.6,0	},
	{	12,3,75.3,32,1,NAN,NAN,1,2.8,0	},
	{	12,6,75.3,32,1,NAN,NAN,1,13.8,0	},
	{	12,9,75.3,32,1,NAN,NAN,1,15,0	},
	{	12,24,75.3,32,1,NAN,NAN,1,10.5,0	},
	{	12,24,75.3,32,1,NAN,NAN,2,25,0	},
	{	12,36,75.3,32,1,NAN,NAN,1,9.1,0	},
	{	12,36,75.3,32,1,NAN,NAN,2,15,0	},
	{	12,48,75.3,32,1,NAN,NAN,1,6.6,0	},
	{	12,48,75.3,32,1,NAN,NAN,2,11,0	},
	{	12,72,75.3,32,1,NAN,NAN,1,4.9,0	},
	{	12,72,75.3,32,1,NAN,NAN,2,NAN,1	},
	{	12,96,75.3,32,1,NAN,NAN,1,2.4,0	},
	{	12,96,75.3,32,1,NAN,NAN,2,NAN,1	},
	{	12,120,75.3,32,1,NAN,NAN,1,1.9,0	},
	{	12,120,75.3,32,1,NAN,NAN,2,NAN,1	},
	{	12,144,75.3,32,1,NAN,NAN,2,NAN,1	},
	{	13,0,75.3,63,1,113,0,0,NAN,1	},
	{	13,0,75.3,63,1,NAN,NAN,2,88,0	},
	{	13,0.5,75.3,63,1,NAN,NAN,1,NAN,1	},
	{	13,1.5,75.3,63,1,NAN,NAN,1,3.6,0	},
	{	13,2,75.3,63,1,NAN,NAN,1,NAN,1	},
	{	13,3,75.3,63,1,NAN,NAN,1,12.9,0	},
	{	13,6,75.3,63,1,NAN,NAN,1,12.9,0	},
	{	13,9,75.3,63,1,NAN,NAN,1,10.2,0	},
	{	13,24,75.3,63,1,NAN,NAN,1,6.4,0	},
	{	13,24,75.3,63,1,NAN,NAN,2,41,0	},
	{	13,36,75.3,63,1,NAN,NAN,1,6.9,0	},
	{	13,36,75.3,63,1,NAN,NAN,2,23,0	},
	{	13,48,75.3,63,1,NAN,NAN,1,4.5,0	},
	{	13,48,75.3,63,1,NAN,NAN,2,16,0	},
	{	13,72,75.3,63,1,NAN,NAN,1,3.2,0	},
	{	13,72,75.3,63,1,NAN,NAN,2,14,0	},
	{	13,96,75.3,63,1,NAN,NAN,1,2.4,0	},
	{	13,96,75.3,63,1,NAN,NAN,2,18,0	},
	{	13,120,75.3,63,1,NAN,NAN,1,1.3,0	},
	{	13,120,75.3,63,1,NAN,NAN,2,22,0	},
	{	13,144,75.3,63,1,NAN,NAN,2,35,0	},
	{	14,0,50,36,0,75,0,0,NAN,1	},
	{	14,0,50,36,0,NAN,NAN,2,85,0	},
	{	14,0.5,50,36,0,NAN,NAN,1,0,0	},
	{	14,1,50,36,0,NAN,NAN,1,2.7,0	},
	{	14,2,50,36,0,NAN,NAN,1,11.6,0	},
	{	14,3,50,36,0,NAN,NAN,1,11.6,0	},
	{	14,6,50,36,0,NAN,NAN,1,11.3,0	},
	{	14,9,50,36,0,NAN,NAN,1,9.7,0	},
	{	14,24,50,36,0,NAN,NAN,1,6.5,0	},
	{	14,24,50,36,0,NAN,NAN,2,32,0	},
	{	14,36,50,36,0,NAN,NAN,1,5.2,0	},
	{	14,36,50,36,0,NAN,NAN,2,22,0	},
	{	14,48,50,36,0,NAN,NAN,1,3.6,0	},
	{	14,48,50,36,0,NAN,NAN,2,21,0	},
	{	14,72,50,36,0,NAN,NAN,1,2.4,0	},
	{	14,72,50,36,0,NAN,NAN,2,28,0	},
	{	14,96,50,36,0,NAN,NAN,1,0.9,0	},
	{	14,96,50,36,0,NAN,NAN,2,38,0	},
	{	14,120,50,36,0,NAN,NAN,1,NAN,1	},
	{	14,120,50,36,0,NAN,NAN,2,46,0	},
	{	14,144,50,36,0,NAN,NAN,2,65,0	},
	{	15,0,56.7,27,0,85,0,0,NAN,1	},
	{	15,0,56.7,27,0,NAN,NAN,2,100,0	},
	{	15,1,56.7,27,0,NAN,NAN,1,6.6,0	},
	{	15,3,56.7,27,0,NAN,NAN,1,11.9,0	},
	{	15,6,56.7,27,0,NAN,NAN,1,11.7,0	},
	{	15,9,56.7,27,0,NAN,NAN,1,12.2,0	},
	{	15,24,56.7,27,0,NAN,NAN,1,8.1,0	},
	{	15,24,56.7,27,0,NAN,NAN,2,43,0	},
	{	15,36,56.7,27,0,NAN,NAN,1,7.4,0	},
	{	15,36,56.7,27,0,NAN,NAN,2,26,0	},
	{	15,48,56.7,27,0,NAN,NAN,1,6.8,0	},
	{	15,48,56.7,27,0,NAN,NAN,2,15,0	},
	{	15,72,56.7,27,0,NAN,NAN,1,5.3,0	},
	{	15,72,56.7,27,0,NAN,NAN,2,13,0	},
	{	15,96,56.7,27,0,NAN,NAN,1,3,0	},
	{	15,96,56.7,27,0,NAN,NAN,2,21,0	},
	{	15,120,56.7,27,0,NAN,NAN,1,2,0	},
	{	15,120,56.7,27,0,NAN,NAN,2,28,0	},
	{	15,144,56.7,27,0,NAN,NAN,2,39,0	},
	{	16,0,58,22,1,87,0,0,NAN,1	},
	{	16,0,58,22,1,NAN,NAN,2,100,0	},
	{	16,24,58,22,1,NAN,NAN,1,10.4,0	},
	{	16,24,58,22,1,NAN,NAN,2,42,0	},
	{	16,36,58,22,1,NAN,NAN,1,8.9,0	},
	{	16,36,58,22,1,NAN,NAN,2,32,0	},
	{	16,48,58,22,1,NAN,NAN,1,7,0	},
	{	16,48,58,22,1,NAN,NAN,2,26,0	},
	{	16,72,58,22,1,NAN,NAN,1,4.4,0	},
	{	16,72,58,22,1,NAN,NAN,2,31,0	},
	{	16,96,58,22,1,NAN,NAN,1,3.2,0	},
	{	16,96,58,22,1,NAN,NAN,2,33,0	},
	{	16,120,58,22,1,NAN,NAN,1,2.4,0	},
	{	16,120,58,22,1,NAN,NAN,2,54,0	},
	{	17,0,78,28,1,117,0,0,NAN,1	},
	{	17,0,78,28,1,NAN,NAN,2,100,0	},
	{	17,24,78,28,1,NAN,NAN,1,7.6,0	},
	{	17,24,78,28,1,NAN,NAN,2,35,0	},
	{	17,36,78,28,1,NAN,NAN,1,6.4,0	},
	{	17,36,78,28,1,NAN,NAN,2,23,0	},
	{	17,48,78,28,1,NAN,NAN,1,6,0	},
	{	17,48,78,28,1,NAN,NAN,2,17,0	},
	{	17,72,78,28,1,NAN,NAN,1,4,0	},
	{	17,72,78,28,1,NAN,NAN,2,18,0	},
	{	17,96,78,28,1,NAN,NAN,1,3.1,0	},
	{	17,96,78,28,1,NAN,NAN,2,18,0	},
	{	17,120,78,28,1,NAN,NAN,1,2,0	},
	{	17,120,78,28,1,NAN,NAN,2,21,0	},
	{	18,0,74.7,31,1,112,0,0,NAN,1	},
	{	18,0,74.7,31,1,NAN,NAN,2,100,0	},
	{	18,24,74.7,31,1,NAN,NAN,1,7.6,0	},
	{	18,24,74.7,31,1,NAN,NAN,2,32,0	},
	{	18,36,74.7,31,1,NAN,NAN,1,6.6,0	},
	{	18,36,74.7,31,1,NAN,NAN,2,20,0	},
	{	18,48,74.7,31,1,NAN,NAN,1,5.4,0	},
	{	18,48,74.7,31,1,NAN,NAN,2,18,0	},
	{	18,72,74.7,31,1,NAN,NAN,1,3.4,0	},
	{	18,72,74.7,31,1,NAN,NAN,2,18,0	},
	{	18,96,74.7,31,1,NAN,NAN,1,1.2,0	},
	{	18,96,74.7,31,1,NAN,NAN,2,19,0	},
	{	18,120,74.7,31,1,NAN,NAN,1,0.9,0	},
	{	18,120,74.7,31,1,NAN,NAN,2,29,0	},
	{	19,0,63.7,22,1,95.5,0,0,NAN,1	},
	{	19,0,63.7,22,1,NAN,NAN,2,100,0	},
	{	19,24,63.7,22,1,NAN,NAN,1,6.6,0	},
	{	19,24,63.7,22,1,NAN,NAN,2,33,0	},
	{	19,36,63.7,22,1,NAN,NAN,1,5.3,0	},
	{	19,36,63.7,22,1,NAN,NAN,2,28,0	},
	{	19,48,63.7,22,1,NAN,NAN,1,3.6,0	},
	{	19,48,63.7,22,1,NAN,NAN,2,18,0	},
	{	19,72,63.7,22,1,NAN,NAN,1,2.7,0	},
	{	19,72,63.7,22,1,NAN,NAN,2,18,0	},
	{	19,96,63.7,22,1,NAN,NAN,1,1.4,0	},
	{	19,96,63.7,22,1,NAN,NAN,2,17,0	},
	{	19,120,63.7,22,1,NAN,NAN,1,1.1,0	},
	{	19,120,63.7,22,1,NAN,NAN,2,26,0	},
	{	20,0,59,22,1,88.5,0,0,NAN,1	},
	{	20,0,59,22,1,NAN,NAN,2,100,0	},
	{	20,24,59,22,1,NAN,NAN,1,9.6,0	},
	{	20,24,59,22,1,NAN,NAN,2,41,0	},
	{	20,36,59,22,1,NAN,NAN,1,8,0	},
	{	20,36,59,22,1,NAN,NAN,2,30,0	},
	{	20,48,59,22,1,NAN,NAN,1,6.6,0	},
	{	20,48,59,22,1,NAN,NAN,2,22,0	},
	{	20,72,59,22,1,NAN,NAN,1,5.6,0	},
	{	20,72,59,22,1,NAN,NAN,2,23,0	},
	{	20,96,59,22,1,NAN,NAN,1,3.5,0	},
	{	20,96,59,22,1,NAN,NAN,2,23,0	},
	{	20,120,59,22,1,NAN,NAN,1,2.3,0	},
	{	20,120,59,22,1,NAN,NAN,2,35,0	},
	{	21,0,62,27,1,93,0,0,NAN,1	},
	{	21,0,62,27,1,NAN,NAN,2,100,0	},
	{	21,24,62,27,1,NAN,NAN,1,7.3,0	},
	{	21,24,62,27,1,NAN,NAN,2,46,0	},
	{	21,36,62,27,1,NAN,NAN,1,6.1,0	},
	{	21,36,62,27,1,NAN,NAN,2,27,0	},
	{	21,48,62,27,1,NAN,NAN,1,4.3,0	},
	{	21,48,62,27,1,NAN,NAN,2,22,0	},
	{	21,72,62,27,1,NAN,NAN,1,3.2,0	},
	{	21,72,62,27,1,NAN,NAN,2,36,0	},
	{	21,96,62,27,1,NAN,NAN,1,2.3,0	},
	{	21,96,62,27,1,NAN,NAN,2,40,0	},
	{	21,120,62,27,1,NAN,NAN,1,1.9,0	},
	{	21,120,62,27,1,NAN,NAN,2,44,0	},
	{	22,0,58,22,1,87,0,0,NAN,1	},
	{	22,0,58,22,1,NAN,NAN,2,100,0	},
	{	22,24,58,22,1,NAN,NAN,1,8.9,0	},
	{	22,24,58,22,1,NAN,NAN,2,35,0	},
	{	22,36,58,22,1,NAN,NAN,1,8.4,0	},
	{	22,36,58,22,1,NAN,NAN,2,27,0	},
	{	22,48,58,22,1,NAN,NAN,1,8,0	},
	{	22,48,58,22,1,NAN,NAN,2,23,0	},
	{	22,72,58,22,1,NAN,NAN,1,4.4,0	},
	{	22,72,58,22,1,NAN,NAN,2,27,0	},
	{	22,96,58,22,1,NAN,NAN,1,3.2,0	},
	{	22,96,58,22,1,NAN,NAN,2,43,0	},
	{	22,120,58,22,1,NAN,NAN,1,1.7,0	},
	{	22,120,58,22,1,NAN,NAN,2,43,0	},
	{	23,0,73.3,22,1,110,0,0,NAN,1	},
	{	23,0,73.3,22,1,NAN,NAN,2,100,0	},
	{	23,24,73.3,22,1,NAN,NAN,1,9.8,0	},
	{	23,24,73.3,22,1,NAN,NAN,2,34,0	},
	{	23,36,73.3,22,1,NAN,NAN,1,8.4,0	},
	{	23,36,73.3,22,1,NAN,NAN,2,24,0	},
	{	23,48,73.3,22,1,NAN,NAN,1,6.6,0	},
	{	23,48,73.3,22,1,NAN,NAN,2,15,0	},
	{	23,72,73.3,22,1,NAN,NAN,1,4.8,0	},
	{	23,72,73.3,22,1,NAN,NAN,2,15,0	},
	{	23,96,73.3,22,1,NAN,NAN,1,3.2,0	},
	{	23,96,73.3,22,1,NAN,NAN,2,19,0	},
	{	23,120,73.3,22,1,NAN,NAN,1,2.4,0	},
	{	23,120,73.3,22,1,NAN,NAN,2,19,0	},
	{	24,0,76.7,35,1,115,0,0,NAN,1	},
	{	24,0,76.7,35,1,NAN,NAN,2,88,0	},
	{	24,24,76.7,35,1,NAN,NAN,1,8.2,0	},
	{	24,24,76.7,35,1,NAN,NAN,2,37,0	},
	{	24,36,76.7,35,1,NAN,NAN,1,7.5,0	},
	{	24,36,76.7,35,1,NAN,NAN,2,20,0	},
	{	24,48,76.7,35,1,NAN,NAN,1,6.8,0	},
	{	24,48,76.7,35,1,NAN,NAN,2,20,0	},
	{	24,72,76.7,35,1,NAN,NAN,1,5.5,0	},
	{	24,72,76.7,35,1,NAN,NAN,2,26,0	},
	{	24,96,76.7,35,1,NAN,NAN,1,4.5,0	},
	{	24,96,76.7,35,1,NAN,NAN,2,28,0	},
	{	24,120,76.7,35,1,NAN,NAN,1,3.7,0	},
	{	24,120,76.7,35,1,NAN,NAN,2,50,0	},
	{	25,0,74.7,23,1,112,0,0,NAN,1	},
	{	25,0,74.7,23,1,NAN,NAN,2,100,0	},
	{	25,24,74.7,23,1,NAN,NAN,1,11,0	},
	{	25,24,74.7,23,1,NAN,NAN,2,32,0	},
	{	25,36,74.7,23,1,NAN,NAN,1,10,0	},
	{	25,36,74.7,23,1,NAN,NAN,2,20,0	},
	{	25,48,74.7,23,1,NAN,NAN,1,8.2,0	},
	{	25,48,74.7,23,1,NAN,NAN,2,17,0	},
	{	25,72,74.7,23,1,NAN,NAN,1,6,0	},
	{	25,72,74.7,23,1,NAN,NAN,2,19,0	},
	{	25,96,74.7,23,1,NAN,NAN,1,3.7,0	},
	{	25,96,74.7,23,1,NAN,NAN,2,21,0	},
	{	25,120,74.7,23,1,NAN,NAN,1,2.6,0	},
	{	25,120,74.7,23,1,NAN,NAN,2,30,0	},
	{	26,0,80,23,1,120,0,0,NAN,1	},
	{	26,0,80,23,1,NAN,NAN,2,100,0	},
	{	26,24,80,23,1,NAN,NAN,1,10,0	},
	{	26,24,80,23,1,NAN,NAN,2,41,0	},
	{	26,36,80,23,1,NAN,NAN,1,9,0	},
	{	26,36,80,23,1,NAN,NAN,2,28,0	},
	{	26,48,80,23,1,NAN,NAN,1,7.3,0	},
	{	26,48,80,23,1,NAN,NAN,2,19,0	},
	{	26,72,80,23,1,NAN,NAN,1,5.2,0	},
	{	26,72,80,23,1,NAN,NAN,2,17,0	},
	{	26,96,80,23,1,NAN,NAN,1,3.7,0	},
	{	26,96,80,23,1,NAN,NAN,2,17,0	},
	{	26,120,80,23,1,NAN,NAN,1,2.7,0	},
	{	26,120,80,23,1,NAN,NAN,2,24,0	},
	{	27,0,80,22,1,120,0,0,NAN,1	},
	{	27,0,80,22,1,NAN,NAN,2,100,0	},
	{	27,24,80,22,1,NAN,NAN,1,11.8,0	},
	{	27,24,80,22,1,NAN,NAN,2,32,0	},
	{	27,36,80,22,1,NAN,NAN,1,9.2,0	},
	{	27,36,80,22,1,NAN,NAN,2,21,0	},
	{	27,48,80,22,1,NAN,NAN,1,7.7,0	},
	{	27,48,80,22,1,NAN,NAN,2,19,0	},
	{	27,72,80,22,1,NAN,NAN,1,4.9,0	},
	{	27,72,80,22,1,NAN,NAN,2,22,0	},
	{	27,96,80,22,1,NAN,NAN,1,3.4,0	},
	{	27,96,80,22,1,NAN,NAN,2,33,0	},
	{	27,120,80,22,1,NAN,NAN,1,2.7,0	},
	{	27,120,80,22,1,NAN,NAN,2,46,0	},
	{	28,0,80,22,1,120,0,0,NAN,1	},
	{	28,0,80,22,1,NAN,NAN,2,100,0	},
	{	28,24,80,22,1,NAN,NAN,1,10.1,0	},
	{	28,24,80,22,1,NAN,NAN,2,39,0	},
	{	28,36,80,22,1,NAN,NAN,1,8,0	},
	{	28,36,80,22,1,NAN,NAN,2,25,0	},
	{	28,48,80,22,1,NAN,NAN,1,6,0	},
	{	28,48,80,22,1,NAN,NAN,2,16,0	},
	{	28,72,80,22,1,NAN,NAN,1,4.9,0	},
	{	28,72,80,22,1,NAN,NAN,2,14,0	},
	{	28,96,80,22,1,NAN,NAN,1,3.4,0	},
	{	28,96,80,22,1,NAN,NAN,2,15,0	},
	{	28,120,80,22,1,NAN,NAN,1,2,0	},
	{	28,120,80,22,1,NAN,NAN,2,20,0	},
	{	29,0,102,22,1,153,0,0,NAN,1	},
	{	29,0,102,22,1,NAN,NAN,2,86,0	},
	{	29,24,102,22,1,NAN,NAN,1,8.3,0	},
	{	29,24,102,22,1,NAN,NAN,2,35,0	},
	{	29,36,102,22,1,NAN,NAN,1,7,0	},
	{	29,36,102,22,1,NAN,NAN,2,21,0	},
	{	29,48,102,22,1,NAN,NAN,1,5.6,0	},
	{	29,48,102,22,1,NAN,NAN,2,18,0	},
	{	29,72,102,22,1,NAN,NAN,1,4.1,0	},
	{	29,72,102,22,1,NAN,NAN,2,20,0	},
	{	29,96,102,22,1,NAN,NAN,1,3.1,0	},
	{	29,96,102,22,1,NAN,NAN,2,29,0	},
	{	29,120,102,22,1,NAN,NAN,1,2.2,0	},
	{	29,120,102,22,1,NAN,NAN,2,41,0	},
	{	30,0,70,23,1,105,0,0,NAN,1	},
	{	30,0,70,23,1,NAN,NAN,2,100,0	},
	{	30,24,70,23,1,NAN,NAN,1,9.9,0	},
	{	30,24,70,23,1,NAN,NAN,2,45,0	},
	{	30,36,70,23,1,NAN,NAN,1,7.5,0	},
	{	30,36,70,23,1,NAN,NAN,2,24,0	},
	{	30,48,70,23,1,NAN,NAN,1,6.5,0	},
	{	30,48,70,23,1,NAN,NAN,2,23,0	},
	{	30,72,70,23,1,NAN,NAN,1,4.1,0	},
	{	30,72,70,23,1,NAN,NAN,2,26,0	},
	{	30,96,70,23,1,NAN,NAN,1,2.9,0	},
	{	30,96,70,23,1,NAN,NAN,2,28,0	},
	{	30,120,70,23,1,NAN,NAN,1,2.3,0	},
	{	30,120,70,23,1,NAN,NAN,2,39,0	},
	{	31,0,83.3,24,1,125,0,0,NAN,1	},
	{	31,0,83.3,24,1,NAN,NAN,2,100,0	},
	{	31,24,83.3,24,1,NAN,NAN,1,9.5,0	},
	{	31,24,83.3,24,1,NAN,NAN,2,45,0	},
	{	31,36,83.3,24,1,NAN,NAN,1,7.8,0	},
	{	31,36,83.3,24,1,NAN,NAN,2,30,0	},
	{	31,48,83.3,24,1,NAN,NAN,1,6.4,0	},
	{	31,48,83.3,24,1,NAN,NAN,2,24,0	},
	{	31,72,83.3,24,1,NAN,NAN,1,4.5,0	},
	{	31,72,83.3,24,1,NAN,NAN,2,22,0	},
	{	31,96,83.3,24,1,NAN,NAN,1,3.4,0	},
	{	31,96,83.3,24,1,NAN,NAN,2,28,0	},
	{	31,120,83.3,24,1,NAN,NAN,1,2.5,0	},
	{	31,120,83.3,24,1,NAN,NAN,2,42,0	},
	{	32,0,62,21,1,93,0,0,NAN,1	},
	{	32,0,62,21,1,NAN,NAN,2,100,0	},
	{	32,24,62,21,1,NAN,NAN,1,8.9,0	},
	{	32,24,62,21,1,NAN,NAN,2,36,0	},
	{	32,36,62,21,1,NAN,NAN,1,7.7,0	},
	{	32,36,62,21,1,NAN,NAN,2,27,0	},
	{	32,48,62,21,1,NAN,NAN,1,6.9,0	},
	{	32,48,62,21,1,NAN,NAN,2,24,0	},
	{	32,72,62,21,1,NAN,NAN,1,4.4,0	},
	{	32,72,62,21,1,NAN,NAN,2,23,0	},
	{	32,96,62,21,1,NAN,NAN,1,3.5,0	},
	{	32,96,62,21,1,NAN,NAN,2,20,0	},
	{	32,120,62,21,1,NAN,NAN,1,2.5,0	},
	{	32,120,62,21,1,NAN,NAN,2,22,0	},
};

/* end OPENPMXTRAN_DATA_ARRAY */

typedef struct IMODEL {
/* begin OPENPMXTRAN_IMODEL_FIELDS_DECLARE */
	double V;
	double CL;
	double KA;
	double KOUT;
	double E0;
	double EMAX;
	double C50;
/* end OPENPMXTRAN_IMODEL_FIELDS_DECLARE */
} IMODEL;

static void imodel_init(IMODEL* const _imodel,
						 ADVANSTATE* const _advanstate)
{
	const double* _theta = _advanstate->current.popparam->theta;
	const double* _eta = _advanstate->current.popparam->eta;
	const RECORD* const _record = _advanstate->current.record;

	/* allow access to RECORD fields */
	const double ID = _record->ID;
	(void)ID;
	const double time = _record->time;
	(void)time;
	const double wt = _record->wt;
	(void)wt;
	const double age = _record->age;
	(void)age;
	const double sex = _record->sex;
	(void)sex;
	const double amt = _record->amt;
	(void)amt;
	const double rate = _record->rate;
	(void)rate;
	const double dvid = _record->dvid;
	(void)dvid;
	const double dv = _record->dv;
	(void)dv;
	const double mdv = _record->mdv;
	(void)mdv;

	/* declare and set IMODEL fields */
	double V = _imodel->V;
	double CL = _imodel->CL;
	double KA = _imodel->KA;
	double KOUT = _imodel->KOUT;
	double E0 = _imodel->E0;
	double EMAX = _imodel->EMAX;
	double C50 = _imodel->C50;

#define THETA(i) 		((const double)_theta[(i)-1])
#define ETA(i) 		((const double)_eta[(i)-1])
#define A(i) 			((const double)_advanstate->current.state[(i)-1])
#define INITCOUNT 		pmx_advan_initcount(_advanstate)
#define ALAG(i,t) 		pmx_advan_amtlag(_advanstate, (i)-1, (t))
#define BIOAVAIL(i,f)	pmx_advan_bioavail(_advanstate, (i)-1, (f))
#define STATETIME 		((const double)_advanstate->current,statetime)
#define INITTIME(t) 	pmx_advan_inittime(_advanstate, (t))
#define A_0(i,v) 		pmx_advan_state_init(_advanstate, (i)-1, (v))

/* begin user code to init the IMODEL */
	const double size = wt / 70.;
	const double vscale = pow(size, 1);
	const double cscale = pow(size, 0.75);
	const double kscale = pow(size, -0.25);
	V = THETA(1) * exp(ETA(1)) * vscale;
	CL = THETA(2) * exp(ETA(2)) * cscale;
	KA = THETA(3) * exp(ETA(3)) * kscale;
	E0 = THETA(5) + ETA(5);
	A_0(3, E0);
	EMAX = THETA(6);
	C50 = THETA(7) * exp(ETA(6));
	KOUT = exp(THETA(8));
/* end user code to init the IMODEL */

#undef THETA
#undef ETA
#undef STATE
#undef A
#undef ALAG
#undef BIOAVAIL
#undef STATETIME
#undef INITCOUNT
#undef INITTIME
#undef A_0

	/* set IMODEL fields */
	_imodel->V = V;
	_imodel->CL = CL;
	_imodel->KA = KA;
	_imodel->KOUT = KOUT;
	_imodel->E0 = E0;
	_imodel->EMAX = EMAX;
	_imodel->C50 = C50;
}

typedef struct PREDICTVARS {
	double IPRED;
	double BPRED;
} PREDICTVARS;

static void imodel_diffeqn(double _dadt[],
						   const IMODEL* const _imodel,
						   const RECORD* const _record,
						   const double* const _state,
						   const POPPARAM* const _popparam,
						   const double T)
{
	const double* const _theta = _popparam->theta;
	const double* const _eta = _popparam->eta;
	(void)_record;
	(void)_theta;
	(void)_eta;
	(void)_state;
	(void)T;

	/* allow access to RECORD fields */
	const double ID = _record->ID;
	(void)ID;
	const double time = _record->time;
	(void)time;
	const double wt = _record->wt;
	(void)wt;
	const double age = _record->age;
	(void)age;
	const double sex = _record->sex;
	(void)sex;
	const double amt = _record->amt;
	(void)amt;
	const double rate = _record->rate;
	(void)rate;
	const double dvid = _record->dvid;
	(void)dvid;
	const double dv = _record->dv;
	(void)dv;
	const double mdv = _record->mdv;
	(void)mdv;

	/* declare IMODEL fields */
	const double V = _imodel->V;
	(void)V;
	const double CL = _imodel->CL;
	(void)CL;
	const double KA = _imodel->KA;
	(void)KA;
	const double KOUT = _imodel->KOUT;
	(void)KOUT;
	const double E0 = _imodel->E0;
	(void)E0;
	const double EMAX = _imodel->EMAX;
	(void)EMAX;
	const double C50 = _imodel->C50;
	(void)C50;

#define THETA(i) 	((const double)_theta[i-1])
#define ETA(i) 	((const double)_eta[i-1])
#define STATE(i) 	((const double)_state[i-1])
#define A(i) 		((const double)_state[i-1])
#define DADT(i) 	(_dadt[i-1])

/* begin user code to do the differential equations */
	DADT(1) = -A(1)*KA;
	DADT(2) = A(1)*KA - A(2)*(CL/V);
	double dcp = A(2)/V;
	double deff = dcp/(C50+dcp);
	double pd = 1 - EMAX*deff;
	DADT(3) = E0*KOUT*pd - KOUT*A(3);
/* end user code to do the differential equations */

#undef THETA
#undef ETA
#undef STATE
#undef A
#undef DADT
}

static double imodel_predict(const IMODEL* const _imodel,
							 const PREDICTSTATE* const _current,
							 const double* const _err,
							 PREDICTVARS* _predparams)
{
	const RECORD* const _record = _current->record;
	const double* const _state = _current->state;
	(void) _record;
	(void) _predparams;
	double Y = NAN;

	/* allow access to RECORD fields */
	const double ID = _record->ID;
	(void)ID;
	const double time = _record->time;
	(void)time;
	const double wt = _record->wt;
	(void)wt;
	const double age = _record->age;
	(void)age;
	const double sex = _record->sex;
	(void)sex;
	const double amt = _record->amt;
	(void)amt;
	const double rate = _record->rate;
	(void)rate;
	const double dvid = _record->dvid;
	(void)dvid;
	const double dv = _record->dv;
	(void)dv;
	const double mdv = _record->mdv;
	(void)mdv;

	/* allow access to IMODEL fields */
	const double V = _imodel->V;
	(void)V;
	const double CL = _imodel->CL;
	(void)CL;
	const double KA = _imodel->KA;
	(void)KA;
	const double KOUT = _imodel->KOUT;
	(void)KOUT;
	const double E0 = _imodel->E0;
	(void)E0;
	const double EMAX = _imodel->EMAX;
	(void)EMAX;
	const double C50 = _imodel->C50;
	(void)C50;

	/* declare PREDICTVARS fields */
	double IPRED;
	double BPRED;

#define THETA(i) 	((const double)_theta[i-1])
#define ETA(i) 	((const double)_current->popparam->eta[i-1])
#define A(i) 		((const double)_state[i-1])
#define ERR(i) 	((const double)_err[i-1])
#define EPS(i) 	((const double)_err[i-1])

/* begin user code to do prediction, set Y and PREDICTVARS */
	IPRED = A(2)/V;
	BPRED = A(3);
	if (dvid == 1) Y = IPRED*(1+ERR(1)) + ERR(2);
	if (dvid == 2) Y = BPRED + ERR(3);
/* end user code to do prediction, set Y and PREDICTVARS */

#undef THETA
#undef ETA
#undef STATE
#undef A
#undef ERR

	/* set PREDICTVARS fields */
	_predparams->IPRED = IPRED;
	_predparams->BPRED = BPRED;

	return Y;
}

static bool openpmxtran_data_preprocess_callback(RECORD* _record)
{
	/* set to remove this record from dataset analysis */
	bool remove = false;

	/* allow write access to RECORD fields */
	double ID = _record->ID;
	double time = _record->time;
	double wt = _record->wt;
	double age = _record->age;
	double sex = _record->sex;
	double amt = _record->amt;
	double rate = _record->rate;
	double dvid = _record->dvid;
	double dv = _record->dv;
	double mdv = _record->mdv;

	/* allow user to change data */
	do {
	/* no data preprocess */
	} while (0);

	/* write back RECORD fields */
	_record->ID = ID;
	_record->time = time;
	_record->wt = wt;
	_record->age = age;
	_record->sex = sex;
	_record->amt = amt;
	_record->rate = rate;
	_record->dvid = dvid;
	_record->dv = dv;
	_record->mdv = mdv;

	return remove ? false : true;
}

static OPENPMX openpmx = (OPENPMX) {
	.filename = OPENPMXTRAN_DEFAULT_FILENAME,
	.nthread = 0,
	.data = 
/* begin OPENPMXTRAN_DATA_CONFIG */
	{
		.writeable = OPENPMXTRAN_DATA_NAME,
		.records = OPENPMXTRAN_DATA_NAME,
		.nrecords = 526,
		._offset1 = true,
		.recordfields = {
			.size = sizeof(RECORD),
			.field = {
				{ .name="ID", .offset=offsetof(RECORD, ID) },
				{ .name="time", .offset=offsetof(RECORD, time) },
				{ .name="wt", .offset=offsetof(RECORD, wt) },
				{ .name="age", .offset=offsetof(RECORD, age) },
				{ .name="sex", .offset=offsetof(RECORD, sex) },
				{ .name="amt", .offset=offsetof(RECORD, amt) },
				{ .name="rate", .offset=offsetof(RECORD, rate) },
				{ .name="dvid", .offset=offsetof(RECORD, dvid) },
				{ .name="dv", .offset=offsetof(RECORD, dv) },
				{ .name="mdv", .offset=offsetof(RECORD, mdv) },
			},
		},
	},
/* end OPENPMXTRAN_DATA_CONFIG */
	.advan = {
		.init = imodel_init,
		.predict = imodel_predict,
		.diffeqn = imodel_diffeqn,
		.imodelfields = {
			.size = sizeof(IMODEL),
			.field = {
/* begin OPENPMXTRAN_IMODEL_FIELDINFO */
				{ .name="V", .offset = offsetof(IMODEL, V) },
				{ .name="CL", .offset = offsetof(IMODEL, CL) },
				{ .name="KA", .offset = offsetof(IMODEL, KA) },
				{ .name="KOUT", .offset = offsetof(IMODEL, KOUT) },
				{ .name="E0", .offset = offsetof(IMODEL, E0) },
				{ .name="EMAX", .offset = offsetof(IMODEL, EMAX) },
				{ .name="C50", .offset = offsetof(IMODEL, C50) },
/* end OPENPMXTRAN_IMODEL_FIELDINFO */
			},
		},
		.predictfields = {
			.size = sizeof(PREDICTVARS),
			.field = {
/* begin OPENPMXTRAN_PREDPARAMS_FIELDINFO */
				{ .name="IPRED", .offset = offsetof(PREDICTVARS, IPRED) },
				{ .name="BPRED", .offset = offsetof(PREDICTVARS, BPRED) },
/* end OPENPMXTRAN_PREDPARAMS_FIELDINFO */
			},
		},
/* begin OPENPMXTRAN_ADVAN_INIT */
		.method = pmx_advan_diffeqn_libgsl,
		.nstate = 3,
/* end OPENPMXTRAN_ADVAN_INIT */
	},
	.theta = {
/* begin OPENPMXTRAN_THETA_INIT */
	{ 1,   8,   20, ESTIMATE },
	{ 0,   0.1,   1, ESTIMATE },
	{ 0.01,   0.5,   5, ESTIMATE },
	{ 0, 0, 0, FIXED },
	{ 50,   100,   150, ESTIMATE },	// E0
	{ 0,   1,   5, ESTIMATE },	// EMAX
	{ 0,   2,   5, ESTIMATE },	// C50
	{ -5,   -3,   1, ESTIMATE },	// log(KOUT)
/* end OPENPMXTRAN_THETA_INIT */
	},
	.omega = {
/* begin OPENPMXTRAN_OMEGA_INIT */
			{ OMEGA_DIAG, 6, { 0.1, 0.1, 0.1, 0, 0, 0 } },
/* end OPENPMXTRAN_OMEGA_INIT */
	},
	.sigma = {
/* begin OPENPMXTRAN_SIGMA_INIT */
	1, 1, 100
/* end OPENPMXTRAN_SIGMA_INIT */
	},
};

OPENPMX current(void)
{
	return pmx_copy(&openpmx);
}
void estimate_config(ESTIMCONFIG* estimconfig)
{
	pmx_estimate(&openpmx, estimconfig);
}
#define estimate(...) pmx_estimate(&openpmx, &(ESTIMCONFIG){ __VA_ARGS__ })

void fastestimate_config(ESTIMCONFIG* estimconfig)
{
	pmx_fastestimate(&openpmx, estimconfig);
}
#define fastestimate(...) pmx_fastestimate(&openpmx, &(ESTIMCONFIG){ __VA_ARGS__ })

void evaluate_config(STAGE1CONFIG* stage1config)
{
	pmx_evaluate(&openpmx, stage1config);
}
#define evaluate(...) pmx_evaluate(&openpmx, &(STAGE1CONFIG){ __VA_ARGS__ })

void simulate_config(const SIMCONFIG* simconfig)
{
	pmx_simulate(&openpmx, simconfig);
}
#define simulate(...) pmx_simulate(&openpmx, &(SIMCONFIG){ __VA_ARGS__ })

void predict(void)
{
	pmx_predict(&openpmx);
}

void predict_pred(void)
{
	pmx_predict_pred(&openpmx);
}

#define table(f, ...)	pmx_table(&openpmx, (f), &(TABLECONFIG){ __VA_ARGS__ })

static void openpmxtran_data_preprocess(void)
{
	RECORD* data = openpmx.data.writeable;
	const int nrecords = openpmx.data.nrecords;
	int i = 0;
	int n = 0;
	for (i=0; i<nrecords; i++) {
		RECORD r = data[i];
		if (openpmxtran_data_preprocess_callback(&r)) {
			data[n] = r;
			++n;
		}
	}
	for (i=n; i<nrecords; i++)
		data[n].ID = NAN;
}

int main(void)
{
	/* do any preprocessing defined in the $DATA code */
	openpmxtran_data_preprocess();
//	feenableexcept(FE_DIVBYZERO | FE_INVALID | FE_OVERFLOW);

/* begin OPENPMXTRAN_MAIN_CODE */
	estimate();
/* end OPENPMXTRAN_MAIN_CODE */

	pmx_cleanup(&openpmx);
	return EXIT_SUCCESS;
}
