#!/bin/sh
set -ex

UNAME="$(uname -s)"
PLATFORM="${3:-${UNAME}}"
if [ "${PLATFORM}" = "Linux" ]; then
	BINARY="a.out"
elif [[ "${PLATFORM}" =~ MINGW64_NT-* ]]; then
	BINARY="a.exe"
fi

# ./install pthread static

#(cd examples/c; gcc -W -Wall -Wextra -O2 schnider_advan.c -I../../include -I../../src -lgsl -lgslcblas -lm; ./${BINARY}; rm ${BINARY})
#(cd examples/c; gcc -W -Wall -Wextra -O2 theo.c           -I../../include -I../../src -lgsl -lgslcblas -lm; ./${BINARY}; rm ${BINARY})
#(cd examples/c; gcc -W -Wall -Wextra -O2 theo_advan.c     -I../../include -I../../src -lgsl -lgslcblas -lm; ./${BINARY}; rm ${BINARY})
#(cd examples/c; gcc -W -Wall -Wextra -O2 theo_posthoc.c   -I../../include -I../../src -lgsl -lgslcblas -lm; ./${BINARY}; rm ${BINARY})

#(cd examples/schnider; ../../openpmx schnider.gr)
(cd examples/theo; ../../openpmx theo.gr)
# (cd examples/schnider; ../../openpmx schnider_diffeqn.gr)
#(cd examples/warfarin; ../../openpmx warfarin.gr)

