#!/bin/sh
set -ex
rm a.out | true

../../install pthread static
rm a.out | true; gcc -W -Wall -Wextra -g -O2 theo.c -I../../include -I../../src -lgsl -lgslcblas -lm; ./a.out
rm a.out | true; gcc -W -Wall -Wextra -g -O2 theo_posthoc.c -I../../include -I../../src -lgsl -lgslcblas -lm; ./a.out
rm a.out | true; clang -W -Wall -Wextra -g -O2 theo_posthoc.c -I../../include -I../../src -lgsl -lgslcblas -lm; ./a.out
rm a.out | true

