//
//	Schnider T, Minto C, Gambus P, Andresen C, Goodale D, Shafer S, Youngs E:
//	The influence of method of administration and covariates on the pharmacokinetics
//	of propofol in adult volunteers. Anesthesiology 1998; 88:1170–82 PMID: 9605675
//
//	Data obtained from http://opentci.org/data/propofol/schnider-1998-study (Nov 6 2020)
//	 - changed CP name to DV
//
$DATA(data.csv)
$ADVAN(threecomp) 
	.firstonly = true,
$IMODEL(V1, V2, V3, CL, Q2, Q3)
	const double SIZE = WT/70.;
	V1 = THETA(1) * SIZE * exp(ETA(1));
	V2 = THETA(2) * SIZE * exp(ETA(2) + THETA(7)*(AGE-35)); /* a comment */
	V3 = THETA(3) * SIZE * exp(ETA(3));
	CL = THETA(4) * pow(SIZE, 0.75) * exp(ETA(4));
	Q2 = THETA(5) * pow(V2/THETA(2), 0.75) * exp(ETA(5));
	Q3 = THETA(6) * pow(V3/THETA(3), 0.75) * exp(ETA(6));
$PREDICT(IPRED)
	IPRED = A(1)/V1;
	Y = IPRED*(1 + ERR(1));
$THETA
	{   1,   4,   10,  ESTIMATE     },
	{   5,   20,   50,  ESTIMATE     },
	{   20,   100,   1000,  ESTIMATE     },
	{   0.1,   2,   5,  ESTIMATE     },
	{   0.1,   2,   5,  ESTIMATE     },
	{   0.1,   1,   5,  ESTIMATE     },
	{   -.1,   0,   .1,  ESTIMATE     },
$OMEGA(0.1, 0.1, 0.1, 0.1, 0., 0.)
$SIGMA(0.1)
$FUNCTIONS
void do_profile(const int type, 
				const int index, 
				const double lower, 
				const double upper, 
				const char* name)
{
	PROFILECONFIG p = {
		.type = type,
		.index = index,
		.value = lower,
		.dobjfn = 15.,
		.name = name,
	};
	profile(&p);
	double left = p.value;

	p.value = upper;
	p.append = true;
	profile(&p);
	double right = p.value;
	
	p.maxeval = 1;
	for (p.value=left; p.value<=right; p.value+=(right-left)/10.) 
		profile(&p);
}
$MAIN
	estimate();
	
	do_profile(PROFILE_THETA, 1, 1, 40, "V1");
	do_profile(PROFILE_THETA, 2, 5, 100, "V2");
	do_profile(PROFILE_THETA, 3, 100, 400, "V3");
	do_profile(PROFILE_THETA, 4, .1, 4, "CL");
	do_profile(PROFILE_THETA, 5, .1, 4, "Q2");
	do_profile(PROFILE_THETA, 6, .1, 4, "Q3");

	
	
